# Generated by Django 4.2.3 on 2024-11-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_option_add_time_poll_add_time_response_add_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
