# Generated by Django 4.2.3 on 2024-11-29 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_option_add_time_alter_poll_add_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='add_time',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='add_time',
        ),
        migrations.RemoveField(
            model_name='response',
            name='add_time',
        ),
    ]
