# Generated by Django 4.2.3 on 2024-11-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_option_add_time_remove_poll_add_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='upload_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
